print("Введите свои данные для заполнения карточки студента")
surname = input("Фамилия: ")
name = input("Имя: ")
group = input("Номер группы: ")
city = input("Город: ")
age = int(input("Возраст: "))
subject = input("Любимый предмет: ")
hours = float(input("Количество часов в неделю: "))
print("----------")
print("Карточка студента")
print("Полное имя: ",name,surname)
print(f"Возраст в конце обучения: {age+4}")
print(f"Время обучения за 4 недели: {hours*4:.2f}")
print(f"Среднее время в день: {hours/7:.2f}")
print("----------")

